### ISSUE TITLE
Prisma 5 released - breaks generated types

### ISSUE THREAD

**Issue by jasonmacdonald** [unlight/prisma-nestjs-graphql#177] opened 2023-07-12 18:14 UTC
It looks like the changes introduced in V5 of Prisma break the generated files from this.  Lots of `* is not assignable to type *` type errors. I guess it's because of the changes to carry shortcuts, but it might be something else. I've tried searching through, but I got in a bit of looping trying to find the exact reason.

https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#removal-of-array-shortcuts

**Comment by jasonmacdonald** [comment] 2023-07-12 18:43
It looks like they are now wrapping certain types in a `Prisma.AtLeast<{...classProps}, "prop1" | "prop1">` function which makes certain properties required if they are, I assume, `@id`,  `@@id` or `@unique` in the schema.

**Comment by magrinj** [comment] 2023-07-21 12:39
@unlight I make a PR, hope it's the correct way to fix it

**Comment by unlight** [comment] 2023-07-24 21:29
@jasonmacdonald @jasonmacdonald 
Please check version 19 (use next dist-tag)
```
npm i prisma-nestjs-graphql@next
```

**Comment by unlight** [comment] 2023-07-24 21:31
@jasonmacdonald @magrinj  @Siumauricio
Please check version 19 (use next dist-tag) with prisma 5
```
npm i prisma-nestjs-graphql@next
```

**Comment by magrinj** [comment] 2023-07-25 06:48
Hi @unlight, thanks a lot, I will take a look today :) 
Didn't had time to fix tests issues yesterday, but it seems you fix them

**Comment by jasonmacdonald** [comment] 2023-08-03 14:19
@unlight Unfortunately, I'm still getting errors in any `WHere` class with an `AND` etc., as they are self-references and therefore it's not wrapped. So we need to also add it to those.

```
export declare class SomeClassWhereUniqueInput {
    AND?: Array<SomeClassWhereUniqueInput>;
    OR?: Array<SomeClassWhereUniqueInput>;
    NOT?: Array<SomeClassWhereUniqueInput>;
}
 ```
    
 I think the issue is that we are wrapping the `where: Prisma.AtLeast<SomeCLasseUniqueInput, 'id'>;` instead of the actual type like Prisma does.
    
``` 
 export typeSOmeClassWhereUniqueInput = Prisma.AtLeast<{
    id?: string
    id_accountId?: TrainingTaskIdAccountIdCompoundUniqueInput
    AND?: TrainingTaskWhereInput | TrainingTaskWhereInput[]
    OR?: TrainingTaskWhereInput[]
    NOT?: TrainingTaskWhereInput | TrainingTaskWhereInput[]
    ...
}
```

**Comment by unlight** [comment] 2023-08-05 16:00
@jasonmacdonald 
Please provide example schema, how can I reproduce it.

**Comment by ysuhaas** [comment] 2023-09-06 13:47
@jasonmacdonald Curious if you ended up finding a workaround here? We are seeing the same issue in our project as well

**Comment by jasonmacdonald** [comment] 2023-09-07 22:57
> @jasonmacdonald Curious if you ended up finding a workaround here? We are seeing the same issue in our project as well

We held off upgrading due to some other reasons, but this issue still exists for us as well. I haven't had a chance to dig deeper though.

**Comment by bigfree** [comment] 2023-09-08 13:16
I have same problem
```typescript
findOne(userWhereUniqueInput: UserWhereUniqueInput) {
    return this.prisma.user.findUnique({
        where: userWhereUniqueInput,
    }) as Promise<User>;
}
```

Here is type error:
```
Type 'UserWhereUniqueInput' is not assignable to type '{ id: string; email: string; } & { id?: string | undefined; email?: string | undefined; AND?: UserWhereInput | UserWhereInput[] | undefined; OR?: UserWhereInput[] | undefined; NOT?: UserWhereInput | ... 1 more ... | undefined; password?: string | ... 1 more ... | undefined; createdAt?: string | ... 3 more ... | unde...'.
Type  UserWhereUniqueInput  is not assignable to type  { id: string; email: string; } 
Types of property  id  are incompatible.
Type  string | undefined  is not assignable to type  string 
Type  undefined  is not assignable to type  string 
index.d.ts(1471, 5): The expected type comes from property  where  which is declared here on type
```

Prisma model
```prisma
model User {
  /// @HideField({ match: 'User*@(Create|Update)*Input' })
  id        String    @id @default(cuid())
  email     String    @unique @db.VarChar(255)
  password  String
  /// @HideField({ output: false, input: true })
  createdAt DateTime? @default(now())
  /// @HideField({ output: false, input: true })
  updatedAt DateTime? @updatedAt
}
```

Here is generate prisma **UserWhereUniqueInput**
```typescript
export type UserWhereUniqueInput = Prisma.AtLeast<{
    id?: string
    email?: string
    AND?: UserWhereInput | UserWhereInput[]
    OR?: UserWhereInput[]
    NOT?: UserWhereInput | UserWhereInput[]
    password?: StringFilter<"User"> | string
    createdAt?: DateTimeNullableFilter<"User"> | Date | string | null
    updatedAt?: DateTimeNullableFilter<"User"> | Date | string | null
}, "id" | "email">
```

And here prisma-nestjs-graphql **UserWhereUniqueInput**
```typescript
import { Field } from '@nestjs/graphql';
import { InputType } from '@nestjs/graphql';
import { UserWhereInput } from './user-where.input';
import { StringFilter } from '../prisma/string-filter.input';
import { DateTimeNullableFilter } from '../prisma/date-time-nullable-filter.input';
import { HideField } from '@nestjs/graphql';

@InputType()
export class UserWhereUniqueInput {

    @Field(() => String, {nullable:true})
    id?: string;

    @Field(() => String, {nullable:true})
    email?: string;

    @Field(() => [UserWhereInput], {nullable:true})
    AND?: Array<UserWhereInput>;

    @Field(() => [UserWhereInput], {nullable:true})
    OR?: Array<UserWhereInput>;

    @Field(() => [UserWhereInput], {nullable:true})
    NOT?: Array<UserWhereInput>;

    @Field(() => StringFilter, {nullable:true})
    password?: StringFilter;

    @HideField()
    createdAt?: DateTimeNullableFilter;

    @HideField()
    updatedAt?: DateTimeNullableFilter;
}

any idea?
```

**Comment by unlight** [comment] 2023-09-16 17:43
@bigfree Thank you for example.

Yes, UserWhereUniqueInput and Prisma.UserWhereUniqueInput are incompatible
But GraphQL doesnt have 'oneOf' feature (e.g. https://gatographql.com/guides/augment/oneof-input-object/)

From my POV, generated class is valid, I do not see how it can be fixed in terms of compatibility.
So, I think you should add additional validation logic to your method.

For example:

```ts
findOne(userWhereUniqueInput: UserWhereUniqueInput) {
    // Validate that userWhereUniqueInput has id, email other unique key
    const validatedUserWhereUniqueInput = userWhereUniqueInput as Prisma.AtLeast<UserWhereUniqueInput, ...>;
    return this.prisma.user.findUnique({ where: validatedUserWhereUniqueInput });
}
```

```ts
  // Pseudo code
  @UsePipes(new ValidateAtLeastIdOrEmail())
  findOne(userWhereUniqueInput: Prisma.AtLeast<UserWhereUniqueInput, 'id' | 'email'>) {
    $prisma.user.findUnique({ where: userWhereUniqueInput }); // OK
  }
```


```ts
const userWhereUniqueInput: UserWhereUniqueInput = {}; // TS OK

$prisma.user.findUnique({ where: userWhereUniqueInput }); // ERROR
$prisma.user.findUnique({ where: userWhereUniqueInput as Prisma.AtLeast<UserWhereUniqueInput, 'id' | 'email'> }); // OK
```

Maybe I may add additional metadata to such classes.
```ts
@InputType()
export class UserWhereUniqueInput {
  @Field(() => String, { nullable: true })
  @Reflect.metadata('AtLeast')
  id?: string;

  @Field(() => Scalars.GraphQLEmailAddress, { nullable: true })
  @Reflect.metadata('AtLeast')
  email?: string;
}

Validator can be created
These metadata can be automatically

**Comment by unlight** [comment] 2023-09-16 17:54
Another idea I can intoduce new option in config to trick typescript and add exclamation mark for all unique fields for such WhereUniqueInput classes.
```ts
@InputType()
export class UserWhereUniqueInput {
  @Field(() => String, { nullable: true })
  id!: string;

  @Field(() => Scalars.GraphQLEmailAddress, { nullable: true })
  email!: string;
}
```

**Comment by isaacpz** [comment] 2023-09-19 01:44
> Another idea - introduce new option in config to trick typescript and add exclamation mark for all unique fields for such WhereUniqueInput classes (unsafe, needs validation and coercing to valid type).

If helpful, I think we'd choose this solution! Maybe this should be hidden behind some configuration flag since it sacrifices some type safety and let the user choose the solution they want?

**Comment by bigfree** [comment] 2023-09-19 11:03
@unlight Thx for you response. I'll try type assertion, but it's a bit messy in the code. I'm in for a switch in the configuration even if it is a bit unsafe.

**Comment by jasonmacdonald** [comment] 2023-09-20 16:17
> @unlight Unfortunately, I'm still getting errors in any `WHere` class with an `AND` etc., as they are self-references and, therefore, not wrapped with the `Prisma.AtLeast`. So we need to also add it to those.
> 
> ```
> export declare class SomeClassWhereUniqueInput {
>     AND?: Array<SomeClassWhereUniqueInput>;
>     OR?: Array<SomeClassWhereUniqueInput>;
>     NOT?: Array<SomeClassWhereUniqueInput>;
> }
> ```
> 
> I think the issue is that we are wrapping the `where: Prisma.AtLeast<SomeCLasseUniqueInput, 'id'>;` instead of the actual type like Prisma does.
> 
> ```
>  export type SomeClassWhereUniqueInput = Prisma.AtLeast<{
>     id?: string
>     AND?: SomeClassWhereUniqueInput | SomeClassWhereUniqueInput[]
>     OR?: SomeClassWhereUniqueInput[]
>     NOT?: SomeClassWhereUniqueInput | SomeClassWhereUniqueInput[]
>     ...
> }
> ```

@unlight  update on the issue I posted a while back. I finally had time to look deeper into the matter; a custom `InputType` in our code was the cause. We had created one that was not using `AtLeast` properly when including a unique input created by this library. It was tricky to hunt down due to the overly verbose nested typescript errors. Once I fixed the aforementioned input, everything worked as expected. Sorry for the false alarm.

@ysuhaas, if you are still getting a similar issue, try checking any custom `InputType` or `ObjectTypes` you have.

**Closed** 2023-09-23 17:00 UTC
Labels: enhancement, help wanted, released on @next

**Comment by simonjoom** [comment] 2024-03-18 01:43
I got the same problem using last type-graphql and last prisma 

for me  what i did: 
when the class got only one @unique field id in his model, change the ? to the exclamation class

@InputType()
export class UserWhereUniqueInput {
  @Field(() => String, { nullable: true })
  id!: string;

  @Field(() => String, { nullable: true })
  fieldoptional?: string;
}


but if there is 2 unique

you will need to change all relations :  (here unique type are id and email)
where!: UserWhereUniqueInput;
to
 where!: Prisma.AtLeast<UserWhereUniqueInput, 'id' | 'email'>;

and also for relation connect (here unique type are id and name)
  connect?: CountryWhereUniqueInput | undefined;

  connect?: Prisma.AtLeast<CountryWhereUniqueInput,"id"|"name"> | undefined;

Seems the last code prisma-nestjs-graphql fix that, but would be great that the generator https://github.com/MichalLytek/typegraphql-prisma do that by default i think
